# Usar una imagen base de OpenJDK 21
FROM openjdk:21-jdk-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el wrapper de Maven y el archivo pom.xml al contenedor
COPY pom.xml mvnw ./
COPY .mvn/ .mvn

# Descargar las dependencias usando el wrapper de Maven
#RUN ./mvnw dependency:go-offline -B
RUN ./mvnw dependency:resolve dependency:resolve-plugins -B

# Copiar el código fuente de la aplicación al contenedor
#COPY src ./src

# Compilar la aplicación (sin tests en dev para velocidad)
#RUN ./mvnw -B clean package -DskipTests

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 8082

# Comando para ejecutar la aplicación
#CMD ["java", "-jar", "target/kafka-consumer-service-0.0.1-SNAPSHOT.jar"]
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.arguments=\"--kafka.topics=demo-topic,another-topic\""]
